# This workflow will install Python dependencies, run tests, and lint with a single version of Python
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Run 'make install' to set up dependencies using your Makefile
    - name: Install dependencies
      run: |
        make install

    # Run 'make run' to start the Flask server
    - name: Run application
      run: |
        make run &
        sleep 10  # Sleep to allow the server to start

    # Check if the application is running
    - name: Check if application is running
      run: |
        curl http://localhost:3000 || exit 1

    # Lint the code with flake8
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Run tests using pytest
    - name: Test with pytest
      run: |
        pytest
